In [2]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121


In [3]:
import torch
from tokenizer import Tokenizer
from model import Model

In [4]:
my_tokenizer = Tokenizer("tokenizer.json")
tokens = my_tokenizer.encode("Merhaba, senin adın ne söyleyebilir misin?")
torch.manual_seed(2)
model = Model(len(my_tokenizer.vocab), embedding_dim=4,device='cpu')
sentence_meaning=model(tokens)
sentence_meaning.shape

torch.Size([1, 24, 4])

In [5]:
sentence_meaning=sentence_meaning.squeeze()
sentence_meaning.shape[0]

24

In [6]:
all_similarities= torch.zeros((sentence_meaning.shape[0],sentence_meaning.shape[0]))

for i in range(sentence_meaning.shape[0]):
    similarities = []
    for j in range(sentence_meaning.shape[0]):
        sim = sentence_meaning[i][0]*sentence_meaning[j][0]+sentence_meaning[i][1]*sentence_meaning[j][1]+sentence_meaning[i][2]*sentence_meaning[j][2]+sentence_meaning[i][3]*sentence_meaning[j][3]
        similarities.append(sim)
    all_similarities[i] = torch.tensor(similarities)
all_similarities.detach().numpy()

array([[ 1.45004582e+00,  7.70409465e-01, -2.00766873e+00,
         4.44395065e-01, -4.11212981e-01, -9.30310547e-01,
        -1.20509911e+00, -9.20015275e-01, -2.38462090e-01,
        -2.15934849e+00, -1.42134786e-01, -1.03868830e+00,
         1.60605204e+00, -2.39195764e-01, -1.78702414e-01,
        -1.75242901e+00, -4.86856610e-01, -2.75929987e-01,
         1.38712823e+00,  3.49406123e-01,  6.96267486e-02,
        -8.06586504e-01,  5.36909640e-01,  5.41329682e-01],
       [ 7.70409465e-01,  3.15727639e+00, -1.70981658e+00,
        -1.87100720e+00, -3.05061936e-02,  2.50172287e-01,
        -6.50799155e-01, -1.01747990e+00, -1.10199618e+00,
        -2.85551548e-02, -1.40715325e+00,  4.16057646e-01,
         1.50139785e+00,  1.86435533e+00, -1.12650740e+00,
         1.61898625e+00, -1.61793065e+00,  3.03179526e+00,
         1.58042336e+00,  1.23984563e+00,  2.06875873e+00,
        -1.33389783e+00,  3.52961016e+00,  4.42744255e-01],
       [-2.00766873e+00, -1.70981658e+00,  3.06806064e

In [7]:
all_similarities= torch.zeros((sentence_meaning.shape[0],sentence_meaning.shape[0]))

for i in range(sentence_meaning.shape[0]):
    i_similarities = torch.zeros(sentence_meaning.shape[0])
    for j in range(sentence_meaning.shape[0]):
        for k in range(sentence_meaning.shape[1]):
            i_similarities[j] += sentence_meaning[i][k]*sentence_meaning[j][k]
    all_similarities[i] = i_similarities
all_similarities.detach().numpy()

array([[ 1.45004582e+00,  7.70409465e-01, -2.00766873e+00,
         4.44395065e-01, -4.11212981e-01, -9.30310547e-01,
        -1.20509911e+00, -9.20015275e-01, -2.38462090e-01,
        -2.15934849e+00, -1.42134786e-01, -1.03868830e+00,
         1.60605204e+00, -2.39195764e-01, -1.78702414e-01,
        -1.75242901e+00, -4.86856610e-01, -2.75929987e-01,
         1.38712823e+00,  3.49406123e-01,  6.96267486e-02,
        -8.06586504e-01,  5.36909640e-01,  5.41329682e-01],
       [ 7.70409465e-01,  3.15727639e+00, -1.70981658e+00,
        -1.87100720e+00, -3.05061936e-02,  2.50172287e-01,
        -6.50799155e-01, -1.01747990e+00, -1.10199618e+00,
        -2.85551548e-02, -1.40715325e+00,  4.16057646e-01,
         1.50139785e+00,  1.86435533e+00, -1.12650740e+00,
         1.61898625e+00, -1.61793065e+00,  3.03179526e+00,
         1.58042336e+00,  1.23984563e+00,  2.06875873e+00,
        -1.33389783e+00,  3.52961016e+00,  4.42744255e-01],
       [-2.00766873e+00, -1.70981658e+00,  3.06806064e

In [8]:
# query, key, value yaklaşımıyla benzerlik hesaplama

sentence_meaning @ sentence_meaning.T # her bir kelime diğer kelimelerle olan benzerlikleri gösterir

tensor([[ 1.4500e+00,  7.7041e-01, -2.0077e+00,  4.4440e-01, -4.1121e-01,
         -9.3031e-01, -1.2051e+00, -9.2002e-01, -2.3846e-01, -2.1593e+00,
         -1.4213e-01, -1.0387e+00,  1.6061e+00, -2.3920e-01, -1.7870e-01,
         -1.7524e+00, -4.8686e-01, -2.7593e-01,  1.3871e+00,  3.4941e-01,
          6.9627e-02, -8.0659e-01,  5.3691e-01,  5.4133e-01],
        [ 7.7041e-01,  3.1573e+00, -1.7098e+00, -1.8710e+00, -3.0506e-02,
          2.5017e-01, -6.5080e-01, -1.0175e+00, -1.1020e+00, -2.8555e-02,
         -1.4072e+00,  4.1606e-01,  1.5014e+00,  1.8644e+00, -1.1265e+00,
          1.6190e+00, -1.6179e+00,  3.0318e+00,  1.5804e+00,  1.2398e+00,
          2.0688e+00, -1.3339e+00,  3.5296e+00,  4.4274e-01],
        [-2.0077e+00, -1.7098e+00,  3.0681e+00, -1.5892e-01,  8.1355e-02,
          1.1617e+00,  1.5592e+00,  1.3085e+00,  5.3619e-01,  2.7077e+00,
          7.0407e-01,  9.5642e-01, -2.3908e+00, -3.2254e-02,  3.1124e-01,
          1.9840e+00,  1.0607e+00, -1.1858e-01, -2.0317e+00,  

In [9]:
# yukarıda her bir kelime diğer kelimelere ne kadar benziyoru gördük şimdi de her bir kelime bu cümle içinde ne kadar önemli

attention_weights = torch.softmax(all_similarities, dim=1)
attention_weights

tensor([[1.3969e-01, 7.0794e-02, 4.4004e-03, 5.1098e-02, 2.1718e-02, 1.2923e-02,
         9.8184e-03, 1.3057e-02, 2.5813e-02, 3.7811e-03, 2.8424e-02, 1.1596e-02,
         1.6327e-01, 2.5795e-02, 2.7403e-02, 5.6799e-03, 2.0136e-02, 2.4864e-02,
         1.3117e-01, 4.6468e-02, 3.5128e-02, 1.4626e-02, 5.6051e-02, 5.6300e-02],
        [1.7767e-02, 1.9330e-01, 1.4876e-03, 1.2661e-03, 7.9761e-03, 1.0561e-02,
         4.2895e-03, 2.9727e-03, 2.7318e-03, 7.9917e-03, 2.0134e-03, 1.2466e-02,
         3.6905e-02, 5.3054e-02, 2.6657e-03, 4.1511e-02, 1.6307e-03, 1.7050e-01,
         3.9940e-02, 2.8412e-02, 6.5087e-02, 2.1664e-03, 2.8050e-01, 1.2803e-02],
        [1.7683e-03, 2.3819e-03, 2.8309e-01, 1.1232e-02, 1.4283e-02, 4.2072e-02,
         6.2608e-02, 4.8726e-02, 2.2509e-02, 1.9743e-01, 2.6623e-02, 3.4265e-02,
         1.2056e-03, 1.2749e-02, 1.7974e-02, 9.5745e-02, 3.8030e-02, 1.1695e-02,
         1.7263e-03, 1.4544e-02, 7.6491e-03, 4.1520e-02, 2.4867e-03, 7.6893e-03],
        [5.3708e-02, 5.30

In [10]:
sentence_context_vectors = attention_weights @ sentence_meaning
sentence_context_vectors

tensor([[-0.4188, -0.4478, -0.3420, -0.0401],
        [-0.1292, -1.1875, -0.5712,  0.7491],
        [ 0.7262,  0.0721,  0.7710,  0.6273],
        [ 0.1840,  0.2298, -0.0664, -0.4631],
        [ 0.3436,  0.0224, -0.0578,  0.4792],
        [ 0.4424, -0.5220,  0.1878,  0.5698],
        [ 0.4790,  0.1029,  0.7142,  0.8819],
        [ 0.3431,  0.2349,  0.7777,  0.7985],
        [ 0.3652, -0.1409, -0.0753, -0.1967],
        [ 0.6039, -0.0822,  1.1160,  1.4816],
        [ 0.1730,  0.0948,  0.3363, -0.0514],
        [ 0.4451, -0.2672,  0.1994,  0.7930],
        [-0.8754, -0.3024, -0.1180,  0.2671],
        [ 0.3477, -1.5518, -0.4211,  0.0313],
        [ 0.3467,  0.0892, -0.0820, -0.0959],
        [ 0.5378, -0.5765,  0.8783,  1.4888],
        [ 0.2889,  0.2410,  0.4251,  0.1304],
        [ 0.2193, -1.5023, -0.2949,  0.5827],
        [ 0.0785, -1.3850, -0.5821, -0.4275],
        [ 0.4344, -2.4122,  0.1661, -1.3097],
        [ 0.1119, -1.1398, -0.3802,  0.5993],
        [ 0.4609,  0.2073,  0.2330

In [11]:
"""u_tokeneizer= Tokenizer("tokenizer.json")
tokens = u_tokeneizer.encode("Merhaba, senin adın ne söyleyebilir misin?")
torch.manual_seed(2)
model= Model(len(u_tokeneizer.vocab), embedding_dim=4,device='cpu')
sentence_meaning= model(tokens)

attention_weights = torch.softmax(sentence_meaning @ sentence_meaning.T, dim=1)
sentence_context_vectors = attention_weights @ sentence_meaning"""

'u_tokeneizer= Tokenizer("tokenizer.json")\ntokens = u_tokeneizer.encode("Merhaba, senin adın ne söyleyebilir misin?")\ntorch.manual_seed(2)\nmodel= Model(len(u_tokeneizer.vocab), embedding_dim=4,device=\'cpu\')\nsentence_meaning= model(tokens)\n\nattention_weights = torch.softmax(sentence_meaning @ sentence_meaning.T, dim=1)\nsentence_context_vectors = attention_weights @ sentence_meaning'

In [15]:
q_weights = torch.nn.Linear(4, 3,bias=False) # 4 boyutlu embeddingi 3 boyuta indiriyoruz
k_weights = torch.nn.Linear(4, 3,bias=False)
v_weights = torch.nn.Linear(4, 3,bias=False)


q_of_sentence = q_weights(sentence_meaning)
k_of_sentence = k_weights(sentence_meaning)
v_of_sentence = v_weights(sentence_meaning)

q_of_sentence.shape, k_of_sentence.shape, v_of_sentence.shape

(torch.Size([24, 3]), torch.Size([24, 3]), torch.Size([24, 3]))

In [ ]:
u_sentences =[
  {  "words":q_of_sentence,
    "labels":my_tokenizer.tokenize(prompt),
    "color":"blue",},
    {
    "words":k_of_sentence,
    "labels":my_tokenizer.tokenize(prompt),
    "color":"red",
    },
    {
    "words":v_of_sentence,
    "labels":my_tokenizer.tokenize(prompt),
    "color":"green",
    }
]